### ISSUE TITLE
not able to download images in highest quality ?

### ISSUE THREAD

**Issue by gorkijatt** [Kent-Lee/deviantart-scraper#1]
before deviantart upgraded there servers to wixmp.. i m not able to crack highest resolution as before by just changing simple patterns.. thanks anyway library is cool

**Comment by kent-lee** [comment]
Sorry I am not quite sure what issues you are facing; could you please provide some examples?

**Comment by kent-lee** [comment]
Since this has been two weeks and no information is provided, I am going to close this issue.
